### ISSUE TITLE
Something wrong with 'TS_data'

### ISSUE THREAD

**Issue by JikC** [megvii-research/OMNet#3]
Thank you for sharing your excellent work. I downloaded the TS_data three times but I couldn't extract it. The error message is "An error occurred while loading the archive.", but the "OS_data" opened successfully. I wonder if it's me or the dataset?

**Comment by 35p32** [comment]
> Thank you for sharing your excellent work. I downloaded the TS_data three times but I couldn't extract it. The error message is "An error occurred while loading the archive.", but the "OS_data" opened successfully. I wonder if it's me or the dataset?

Same with me .   It  means  somthing wrong with the download link

**Comment by hxwork** [comment]
> Thank you for sharing your excellent work. I downloaded the TS_data three times but I couldn't extract it. The error message is "An error occurred while loading the archive.", but the "OS_data" opened successfully. I wonder if it's me or the dataset?

Please refer to my answer in [#Issue4 ](https://github.com/megvii-research/OMNet/issues/4).

**Comment by JikC** [comment]
> > Thank you for sharing your excellent work. I downloaded the TS_data three times but I couldn't extract it. The error message is "An error occurred while loading the archive.", but the "OS_data" opened successfully. I wonder if it's me or the dataset?
> 
> Please refer to my answer in [#Issue4 ](https://github.com/megvii-research/OMNet/issues/4).

Received, thanks.

**Comment by hxwork** [comment]
Hi,

I have re-upload TS_data.zip, and please try to download it again.
