### ISSUE TITLE
TS_data.zip is broken;   Cant extract this zip

### ISSUE THREAD

**Issue by 35p32** [megvii-research/OMNet#4]
Hi，thanks for your excellent paper! it is really amazing and nice。

When I download the TS_data.zip  from the link you provid in the readme  “The download link is   TS_data.zip”
I could not extract it no matter how many times i tried， can you confirm this link please? 

Thanks again for your excellent work!

**Comment by hxwork** [comment]
> Hi，thanks for your excellent paper! it is really amazing and nice。
> 
> When I download the TS_data.zip from the link you provid in the readme “The download link is TS_data.zip” I could not extract it no matter how many times i tried， can you confirm this link please?
> 
> Thanks again for your excellent work!

Hi,

Thanks for your feedback. I am sorry that I uploaded an incomplete TS_data.zip, and I will re-upload it today. You can try to download and extract it again later today or tomorrow.

Hao

**Comment by hxwork** [comment]
Hi,

I have re-upload TS_data.zip, and please try to download it again.
