### ISSUE TITLE
Will you release the Pytorch version?

### ISSUE THREAD

**Issue by wzm2256** [megvii-research/OMNet#9]
Thanks for sharing your code.

I'd like to know wheter you will release the Pytorch version code.

**Comment by hxwork** [comment]
> 

Hi,

Thanks for your interest. We will release our Pytorch code as soon as possible (within 2 weeks).

Hao

**Comment by hxwork** [comment]
> Thanks for sharing your code.
> 
> I'd like to know wheter you will release the Pytorch version code.

Hi,

Our Pytorch implementation is available now. Please refer to [this repo](https://github.com/hxwork/OMNet_Pytorch).

Hao
